### ISSUE TITLE
Right values for 3D landmarks

### ISSUE THREAD

**Issue by kj96** [TimoBolkart/TF_FLAME#15]
In `fit_3D_landmarks.py` , 3D landmark data `/data/landmark_3d.npy` (51,3) is the input 3D detected lanmark position that is fitted.
So, If I generate 3D landmarks (using face_alignment package or some other) its landmark value is depending on the size of the image (greater thn zero). But landmark value in **landmark_3d.npy** are between 0.106573 and -0.108844.
How should I normalize the values?

**Comment by TimoBolkart** [comment]
The 3D landmarks we provide in our demo are extracted from a scan and they have the same unit as FLAME, which is provided in Meters. There are different possibilities 
1) fit to 2D landmarks instead (we provide a demo for this), 
2) normalize the 3D landmarks such that they are in the same unit as the model (for predicted 3D landmarks this might not be feasible), or 
3) optimize for an isotropic scale additionally.

If your 3D landmarks are obtained by estimating them from an image, I would recommend fitting to the 2D landmarks instead. Otherwise you inherit all inaccuracies from the estimated landmark depth.
