### ISSUE TITLE
Can FLAME model close eyes?

### ISSUE THREAD

**Issue by foamliu** [TimoBolkart/TF_FLAME#29]
We'd like to use FLAME model to fit RGB-D photos, but seems unlike BFM, FLAME model never close her/his eyes. Is this observation valid?

**Comment by TimoBolkart** [comment]
FLAME is able to close the eyes / do an eye blink. You can see for instance the demo in the [VOCA](https://github.com/TimoBolkart/voca) repository that animates the eyelids using FLAME. If your fitting does not close the eyes, this is either due to the supervision (i.e. imprecise eye landmarks) or a too high regularization for the expression parameters. Adding an additional loss to minimize the distance between the eyelid keypoints might help in this case.
